apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-prometheus-servicemonitor
  namespace: monitoring
  labels:
    name: nginx-ingress-prometheus-servicemonitor
spec:
  selector:
    matchLabels:
      app: ingress-nginx-controller-prometheus
  namespaceSelector:
    matchNames:
    - ingress-nginx
  endpoints:
  - port: prometheus