---

- hosts: k3s_cluster
  gather_facts: yes
  roles:
    - role: sshkey
    - role: dependencies
    - role: nvme

- hosts: k3s_cluster
  vars:
    k3s_registration_address: rp0.localdomain  # Typically a load balancer. # probably need to change this with metallb + traefik
    k3s_etcd_datastore: true
    k3s_server:
      disable:
        - traefik
        - servicelb
      data-dir: /mnt/extra/k3s
      default-local-storage-path: /mnt/extra/k3s/local-storage
  pre_tasks:
    - name: Set each node to be a control node
      ansible.builtin.set_fact:
        k3s_control_node: true
      when: inventory_hostname in groups['servers']
  roles:
    - role: xanmanning.k3s