---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-default-setting
  namespace: mosquitto-app
data:
  mosquitto.conf: |-
    listener 1883
    allow_anonymous true
    persistence true
    persistence_location /mosquitto/data/
    log_dest file /mosquitto/log/mosquitto.log
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: mosquitto-app
  labels:
    app: mosquitto
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c']
        args:
        - mkdir -p /mosquitto/config/;
          cp /cfg/mosquitto.conf /mosquitto/config/mosquitto.conf;
        volumeMounts:
          - mountPath: /cfg/mosquitto.conf
            name: mosquitto-default-setting
            subPath: mosquitto.conf
          - mountPath: /mosquitto/config
            name: mosquitto-config
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0
        volumeMounts:
          - mountPath: /mosquitto/config
            name: mosquitto-config
          - mountPath: /mosquitto/data
            name: mosquitto-data
          - mountPath: /mosquitto/log
            name: mosquitto-log
      volumes:
      - name: mosquitto-default-setting
        configMap:
          name: mosquitto-default-setting
      - name: mosquitto-data
        emptyDir: {}
      - name: mosquitto-config
        emptyDir: {}
      - name: mosquitto-log
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: mosquitto-app
  name: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
    - name: tcp
      protocol: TCP
      port: 1883
      targetPort: 1883
